[package]
name = "hopper_rust"
version = "0.1.0"
authors = ["David Weis <davidmichaelweis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hopper"

[[bin]]
name = "visualizer"
required-features = ["visualizer"]

[features]
default = ["visualizer"]
visualizer = ["kiss3d"]

[dependencies]
dynamixel-driver = { branch = "main", git = "https://github.com/dmweis/dynamixel-driver" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5.8"
clap = "3.0.0-beta.2"
simplelog = "0.9"
log = "0.4"
mint = "0.5"
nalgebra = { version = "0.26", features = ["serde-serialize"] }
anyhow = "1.0"
tokio = { version = "0.2", features = ["macros", "rt-threaded", "time"], default-features = false }
async-trait = "0.1"
kiss3d = { optional = true, version = "0.31" }
lazy_static = "1.4"
bitflags = "1.2"
gilrs = "0.8"

[dev-dependencies]
approx = "0.4.0"