[package]
name = "hopper_rust"
version = "0.1.0"
authors = ["David Weis <davidmichaelweis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hopper"

[[bin]]
name = "visualizer"
required-features = ["visualizer"]

[[bin]]
name = "remote_controller"
required-features = ["visualizer"]

[features]
default = ["visualizer"]
visualizer = ["kiss3d", "gilrs"]

[dependencies]
dynamixel-driver = { branch = "main", git = "https://github.com/dmweis/dynamixel-driver" }
hopper_face = { branch = "main", git = "https://github.com/dmweis/hopper_face" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5.8"
clap = "3.0.0-beta.2"
simplelog = "0.10"
log = "0.4"
mint = "0.5"
nalgebra = { version = "0.26", features = ["serde-serialize"] }
anyhow = "1.0"
tokio = { version = "1.6", features = ["macros", "rt-multi-thread", "time"], default-features = false }
async-trait = "0.1"
lazy_static = "1.4"
bitflags = "1.2"
last-message-channel = { branch = "main", git = "https://github.com/dmweis/last-message-channel" }
rand = "0.8"
ctrlc = "3.1"
prometheus = "0.12.0"
warp = "0.3"
kiss3d = { optional = true, version = "0.31" }
gilrs = { version = "0.8.0", optional = true }

[dev-dependencies]
approx = "0.4.0"