[package]
name = "hopper_rust"
version = "0.1.0"
authors = ["David Weis <davidmichaelweis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamixel-driver = { branch = "main", git = "https://github.com/dmweis/dynamixel-driver" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
clap = "2.33"
simplelog = "0.7"
log = "0.4"
mint = "0.5.5"
nalgebra = { version = "0.21", features = ["serde-serialize"] }
anyhow = "1.0"
tokio = { version = "0.2", features = ["macros", "rt-threaded", "time"], default-features = false }
async-trait = "0.1"

[dev-dependencies]
assert_approx_eq = "1.1"