[package]
name = "hopper_rust"
version = "0.1.0"
authors = ["David Weis <davidmichaelweis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamixel_driver = { git = "https://github.com/dmweis/dynamixel_driver" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
clap = "2.33"
paho-mqtt = "0.6.0"
simplelog = "0.7"
log = "0.4"
ratelimit = "0.4"
