{
 "title": "Hopper monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Dynamixel voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "hopper_legs_voltage{}" }
   ]
  },
  {
   "title": "Move motors to latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(hopper_body_controller_action_duration_seconds_bucket{method=\"move_motors_to\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Move motors to count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "hopper_body_controller_action_duration_seconds_count{method=\"move_motors_to\"}"
    }
   ]
  },
  {
   "title": "Read Mean Voltage latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(hopper_body_controller_action_duration_seconds_bucket{method=\"read_mean_voltage\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}