#!/bin/bash
set -euo pipefail

while true
do
    echo "Waitinf for mqtt message"
    mosquitto_sub -h homepi -t "hopper/build" -C 1
    sleep 2
    echo "Installing hopper"
    sudo dpkg -i hopper-rust.deb
    echo "Installed new hopper version"
done
