#!/bin/bash
set -euo pipefail

trap "exit" INT
while true
do
    echo "Waiting for mqtt message"
    mosquitto_sub -h homepi -t "hopper/build" -C 1
    echo "Installing hopper"
    sudo dpkg --force-confold -i hopper-rust.deb
    echo "Installed new hopper version"
done
