left_front = [
    0.19700001,
    0.147,
    -0.1,
]
left_middle = [
    0.0,
    0.217,
    -0.1,
]
left_rear = [
    -0.19700001,
    0.147,
    -0.1,
]
right_front = [
    0.19700001,
    -0.147,
    -0.1,
]
right_middle = [
    0.0,
    -0.217,
    -0.1,
]
right_rear = [
    -0.19700001,
    -0.147,
    -0.1,
]
