left_front = [
    0.18,
    0.13,
    -0.1,
]
left_middle = [
    0.0,
    0.19999999,
    -0.1,
]
left_rear = [
    -0.18,
    0.13,
    -0.1,
]
right_front = [
    0.18,
    -0.13,
    -0.1,
]
right_middle = [
    0.0,
    -0.19999999,
    -0.1,
]
right_rear = [
    -0.18,
    -0.13,
    -0.1,
]
