left_front = [
    0.18,
    0.15,
    -0.09,
]
left_middle = [
    0.0,
    0.22,
    -0.09,
]
left_rear = [
    -0.18,
    0.15,
    -0.09,
]
right_front = [
    0.18,
    -0.15,
    -0.09,
]
right_middle = [
    0.0,
    -0.22,
    -0.09,
]
right_rear = [
    -0.18,
    -0.15,
    -0.09,
]
